/*
* Copyright 2018-2020 THALES group. All Rights Reserved.
*
* Project name: LPASDK.
* Platform : Windows, Linux.
* Language : C/C++
*
* Except if otherwise stated in a NOTICE file provided by Thales together with the software, below conditions are applicable by default.
*
* This computer program includes confidential and proprietary information of Thales and is a trade secret of
* Thales. All use, disclosure, and/or reproduction is prohibited unless authorized in writing by Thales.
*
* The computer program is provided "AS IS" without warranty of any kind. Thales makes no
* warranties to any person or entity with respect to the computer program and disclaims all other warranties,
* expressed or implied. Thales expressly disclaims any implied warranty of merchantability, fitness for particular
* purpose and any warranty which may arise from course of performance, course of dealing, or usage of trade. Further
* Thales does not warrant that the computer program will meet requirements or that operation of the computer program
* will be uninterrupted or error-free.
*
*/


#include "lpasdk/api/lpasdk_api.h"

static LPA_API_ERROR_DESCRIPTION _apiErrorDescriptionList[] =
{
    { LPA_NO_ERROR, "LPA_NO_ERROR" },

    //	{ LPA_ERROR_CFG_SE_MEDIA_INCORRECT_READER_NAME_SIZE, "LPA_ERROR_CFG_SE_MEDIA_INCORRECT_READER_NAME_SIZE" },
    //	{ LPA_ERROR_CFG_SE_MEDIA_READER_NAME_IS_NULL, "LPA_ERROR_CFG_SE_MEDIA_READER_NAME_IS_NULL" },
    { LPA_NOT_INITIALIZED, "LPA_NOT_INITIALIZED" },

    { LPA_ERROR_INVALID_PARAMETER, "LPA_ERROR_INVALID_PARAMETER" },
    { LPA_ERROR_INSUFFICIENT_BUFFER, "LPA_ERROR_INSUFFICIENT_BUFFER" },
    { LPA_ERROR_INVALID_SW, "LPA_ERROR_INVALID_SW" },
    { LPA_ERROR_ISDR_NOT_SELECTED, "LPA_ERROR_ISDR_NOT_SELECTED" },
    { LPA_ERROR_SE_MEDIA_NOT_INITIALIZED, "LPA_ERROR_SE_MEDIA_NOT_INITIALIZED" },
    { LPA_ERROR_SE_MEDIA_CONTEXT_NOT_ESTABLISHED, "LPA_ERROR_SE_MEDIA_CONTEXT_NOT_ESTABLISHED" },
    { LPA_ERROR_SE_MEDIA_READER_CONNECTION, "LPA_ERROR_SE_MEDIA_READER_CONNECTION" },
    { LPA_ERROR_SE_MEDIA_CONTEXT_NOT_RELEASED, "LPA_ERROR_SE_MEDIA_CONTEXT_NOT_RELEASED" },
    { LPA_ERROR_SE_MEDIA_READER_NOT_DISCONNECTED, "LPA_ERROR_SE_MEDIA_READER_NOT_DISCONNECTED" },
    { LPA_ERROR_SE_MEDIA_UNABLE_TO_SELECT_ISDR, "LPA_ERROR_SE_MEDIA_UNABLE_TO_SELECT_ISDR" },
    { LPA_ERROR_INVALID_GET_PROFILES_INFO_EXCHANGE, "LPA_ERROR_INVALID_GET_PROFILES_INFO_EXCHANGE" },
    { LPA_ERROR_INVALID_GET_EID_EXCHANGE, "LPA_ERROR_INVALID_GET_EID_EXCHANGE" },
    { LPA_ERROR_INVALID_MEMORY_RESET_EXCHANGE, "LPA_ERROR_INVALID_MEMORY_RESET_EXCHANGE" },
    { LPA_ERROR_INVALID_SET_DEFAULT_SMDP_ADDRESS, "LPA_ERROR_INVALID_SET_DEFAULT_SMDP_ADDRESS" },
    { LPA_ERROR_PARAMETER_NOT_AUTHORIZED, "LPA_ERROR_PARAMETER_NOT_AUTHORIZED" },
    { LPA_ERROR_UNKNOWN_PARAMETER, "LPA_ERROR_UNKNOWN_PARAMETER" },
    { LPA_ERROR_INVALID_PARAMETER_TYPE, "LPA_ERROR_INVALID_PARAMETER_TYPE" },
    { LPA_ERROR_INCORRECT_PARAMETER_TYPE, "LPA_ERROR_INCORRECT_PARAMETER_TYPE" },
    { LPA_ERROR_PARAMETER_INTERNAL_ERROR, "LPA_ERROR_PARAMETER_INTERNAL_ERROR" },
    { LPA_ERROR_UNABLE_TO_INIT_LOG, "LPA_ERROR_UNABLE_TO_INIT_LOG" },
    { LPA_ERROR_MISSING_CONFIG_FILE, "LPA_ERROR_MISSING_CONFIG_FILE" },
    { LPA_ERROR_UNABLE_TO_LOAD_CONFIG_FILE, "LPA_ERROR_UNABLE_TO_LOAD_CONFIG_FILE" },
    { LPA_ERROR_CONFIG_FILE_MISSING_MANDATORY_KEY, "LPA_ERROR_CONFIG_FILE_MISSING_MANDATORY_KEY" },
    { LPA_ERROR_CONFIG_FILE_INCORRECT_KEY_VALUE, "LPA_ERROR_CONFIG_FILE_INCORRECT_KEY_VALUE" },
    { LPA_ERROR_UNABLE_TO_INITIALIZE_LPA_MANAGER, "LPA_ERROR_UNABLE_TO_INITIALIZE_LPA_MANAGER" },
    { LPA_ERROR_UNABLE_TO_INITIALIZE_HTTP_MEDIA , "LPA_ERROR_UNABLE_TO_INITIALIZE_HTTP_MEDIA" },
    { LPA_ERROR_EXTENDED_API_UNAVAILABLE, "LPA_ERROR_EXTENDED_API_UNAVAILABLE" },
    { LPA_ERROR_PROCESSING_ERROR, "LPA_ERROR_PROCESSING_ERROR" },

    // Local Profile Management
    { LPA_ERROR_LOCAL_PROFILE_NOT_FOUND, "LPA_ERROR_LOCAL_PROFILE_NOT_FOUND" },
    { LPA_ERROR_LOCAL_PROFILE_INCORRECT_STATE, "LPA_ERROR_LOCAL_PROFILE_INCORRECT_STATE" },
    { LPA_ERROR_LOCAL_PROFILE_CAT_BUSY, "LPA_ERROR_LOCAL_PROFILE_CAT_BUSY" },
    { LPA_ERROR_LOCAL_PROFILE_UNKNOWN_ERROR, "LPA_ERROR_LOCAL_PROFILE_UNKNOWN_ERROR" },
    { LPA_ERROR_LOCAL_PROFILE_INCORRECT_CARD_RESPONSE, "LPA_ERROR_LOCAL_PROFILE_INCORRECT_CARD_RESPONSE" },
    { LPA_ERROR_LOCAL_PROFILE_NOTHING_TO_DELETE, "LPA_ERROR_LOCAL_PROFILE_NOTHING_TO_DELETE" },
    { LPA_ERROR_LOCAL_PROFILE_UNDEFINED_ERROR, "LPA_ERROR_LOCAL_PROFILE_UNDEFINED_ERROR" },
    { LPA_ERROR_LOCAL_PROFILE_UNABLE_TO_EXTRACT_DATA, "LPA_ERROR_LOCAL_PROFILE_UNABLE_TO_EXTRACT_DATA" },

    { LPA_ERROR_LOCAL_PROFILE_ICCID_OR_AID_NOT_FOUND, "LPA_ERROR_LOCAL_PROFILE_ICCID_OR_AID_NOT_FOUND" },
    { LPA_ERROR_LOCAL_PROFILE_NOT_IN_DISABLE_STATE, "LPA_ERROR_LOCAL_PROFILE_NOT_IN_DISABLE_STATE" },
    { LPA_ERROR_LOCAL_PROFILE_DISALLOWED_BY_POLICY, "LPA_ERROR_LOCAL_PROFILE_DISALLOWED_BY_POLICY" },
    { LPA_ERROR_LOCAL_PROFILE_WRONG_PROFILE_REENABLING, "LPA_ERROR_LOCAL_PROFILE_WRONG_PROFILE_REENABLING" },
    { LPA_ERROR_LOCAL_PROFILE_NOT_IN_ENABLE_STATE, "LPA_ERROR_LOCAL_PROFILE_NOT_IN_ENABLE_STATE" },

    { LPA_ERROR_LOCAL_PROFILE_INVALID_DATA_EXCHANGE, "LPA_ERROR_LOCAL_PROFILE_INVALID_DATA_EXCHANGE" },

    // Notification Management
    { LPA_ERROR_NOTIFICATION_INCORRECT_CARD_RESPONSE, "LPA_ERROR_NOTIFICATION_INCORRECT_CARD_RESPONSE" },
    { LPA_ERROR_NOTIFICATION_NOTHING_TO_DELETE, "LPA_ERROR_NOTIFICATION_NOTHING_TO_DELETE" },
    { LPA_ERROR_NOTIFICATION_UNDEFINED_ERROR, "LPA_ERROR_NOTIFICATION_UNDEFINED_ERROR" },
    { LPA_ERROR_NOTIFICATION_UNKNOWN_ERROR, "LPA_ERROR_NOTIFICATION_UNKNOWN_ERROR" },
    { LPA_ERROR_NOTIFICATION_INVALID_CARD_DATA, "LPA_ERROR_NOTIFICATION_INVALID_CARD_DATA" },


    { LPA_ERROR_DOWNLOAD_PROFILE_PARAMETER_ERROR, "LPA_ERROR_DOWNLOAD_PROFILE_PARAMETER_ERROR" },
    { LPA_ERROR_INVALID_GET_EUICC_INFO, "LPA_ERROR_INVALID_GET_EUICC_INFO" },
    { LPA_ERROR_INVALID_GET_UICC_CHALLENGE, "LPA_ERROR_INVALID_GET_UICC_CHALLENGE" },
    { LPA_ERROR_FAILED_INITIAL_AUTHENTICATION, "LPA_ERROR_FAILED_INITIAL_AUTHENTICATION" },
    { LPA_ERROR_FAILED_AUTHENTICATE_SERVER, "LPA_ERROR_FAILED_AUTHENTICATE_SERVER" },
    { LPA_ERROR_FAILED_AUTHENTICATE_CLIENT, "LPA_ERROR_FAILED_AUTHENTICATE_CLIENT" },
    { LPA_ERROR_AUTHENTICATE_CLIENT_EXCHANGE, "LPA_ERROR_AUTHENTICATE_CLIENT_EXCHANGE" },
    { LPA_ERROR_FAILED_PREPARE_DOWNLOAD, "LPA_ERROR_FAILED_PREPARE_DOWNLOAD" },
    { LPA_ERROR_INVALID_CTX_PARAM, "LPA_ERROR_INVALID_CTX_PARAM" },
    { LPA_ERROR_INVALID_AUTHENTICATE_SERVER_RESPONSE, "LPA_ERROR_INVALID_AUTHENTICATE_SERVER_RESPONSE" },
    { LPA_ERROR_INVALID_PREPARE_DOWNLOAD_RESPONSE, "LPA_ERROR_INVALID_PREPARE_DOWNLOAD_RESPONSE" },
    { LPA_ERROR_FAILED_LOAD_BPP, "LPA_ERROR_FAILED_LOAD_BPP" },
    { LPA_ERROR_INVALID_PIR_RESPONSE, "LPA_ERROR_INVALID_PIR_RESPONSE" },
    { LPA_ERROR_CJSON_PARSE_FAILURE, "LPA_ERROR_CJSON_PARSE_FAILURE" },
    { LPA_ERROR_FAILED_INITIAL_SECURITY_CHANNEL, "LPA_ERROR_FAILED_INITIAL_SECURITY_CHANNEL" },
    { LPA_ERROR_FAILED_CONFIGURE_ISDP, "LPA_ERROR_FAILED_CONFIGURE_ISDP" },
    { LPA_ERROR_FAILED_STORE_META_DATA, "LPA_ERROR_FAILED_STORE_META_DATA" },
    { LPA_ERROR_FAILED_REPLACE_SESSION_KEY, "LPA_ERROR_FAILED_REPLACE_SESSION_KEY" },
    { LPA_ERROR_FAILED_LOAD_PROFILE_ELEMENTS, "LPA_ERROR_FAILED_LOAD_PROFILE_ELEMENTS" },
    { LPA_ERROR_FAILED_GET_BOUND_PROFILE_PACKAGE, "LPA_ERROR_FAILED_GET_BOUND_PROFILE_PACKAGE" },
    { LPA_ERROR_FAILED_SEND_NOTIFICATION_OR_NOT_GET_STATUS_CODE, "LPA_ERROR_FAILED_SEND_NOTIFICATION_OR_NOT_GET_STATUS_CODE" },
    { LPA_ERROR_FAILED_GET_DATA_FROM_ACTIVATION_CODE, "LPA_ERROR_FAILED_GET_DATA_FROM_ACTIVATION_CODE" },
    { LPA_ERROR_GET_INTERNAL_SERVER_ERROR, "LPA_ERROR_GET_INTERNAL_SERVER_ERROR" },
    { LPA_ERROR_INVALID_TRANSACTIONID, "LPA_ERROR_INVALID_TRANSACTIONID" }, 
    { LPA_ERROR_INVALID_SERVERSIGNED1, "LPA_ERROR_INVALID_SERVERSIGNED1" },
    { LPA_ERROR_INVALID_SERVERSIGNATURE1, "LPA_ERROR_INVALID_SERVERSIGNATURE1" },
    { LPA_ERROR_INVALID_EUICCCIPKIDTOBEUSED, "LPA_ERROR_INVALID_EUICCCIPKIDTOBEUSED" },
    { LPA_ERROR_INVALID_SERVERCERTIFICATE, "LPA_ERROR_INVALID_SERVERCERTIFICATE" },
    { LPA_ERROR_INVALID_SERVER_RESPONSE, "LPA_ERROR_INVALID_SERVER_RESPONSE" },
    { LPA_ERROR_FAILED_CANCEL_SESSION, "LPA_ERROR_FAILED_CANCEL_SESSION" },
    { LPA_ERROR_INVALID_PROFILE_METADATA, "LPA_ERROR_INVALID_PROFILE_METADATA" },
    { LPA_ERROR_INVALID_GET_RAT, "LPA_ERROR_INVALID_GET_RAT" },
    { LPA_ERROR_PPR_NOT_ALLOWED, "LPA_ERROR_PPR_NOT_ALLOWED" },
    { LPA_ERROR_DOWNLOAD_SESSION_CANCELED_BY_USER, "LPA_ERROR_DOWNLOAD_SESSION_CANCELED_BY_USER" },
    { LPA_ERROR_OID_MISMATCH, "LPA_ERROR_OID_MISMATCH" },
    { LPA_ERROR_INVALID_BPP_DATA, "LPA_ERROR_INVALID_BPP_DATA" },
         
    
    { LPA_ERROR_SERVER_COMMUNICATION_ISSUE,"LPA_ERROR_SERVER_COMMUNICATION_ISSUE"},
    { LPA_ERROR_INVALID_ACTIVATION_CODE,"LPA_ERROR_INVALID_ACTIVATION_CODE"},
    { LPA_ERROR_INVALID_MATCHINGID_OR_DEVICE_INFO_TLV,"LPA_ERROR_INVALID_MATCHINGID_OR_DEVICE_INFO_TLV" },
    { LPA_ERROR_INVALID_DEVICE_INFO_TLV,"LPA_ERROR_INVALID_DEVICE_INFO_TLV" },
    { LPA_ERROR_INVALID_GET_EUICC_ADDRESS,"LPA_ERROR_INVALID_GET_EUICC_ADDRESS" },
    { LPA_ERROR_INVALID_GET_SMDP_ADDRESS,"LPA_ERROR_INVALID_GET_SMDP_ADDRESS" },
    { LPA_ERROR_INVALID_SERVER_ADDRESS,"LPA_ERROR_INVALID_SERVER_ADDRESS" },
    { LPA_ERROR_INVALID_GET_SMDS_ADDRESS,"LPA_ERROR_INVALID_GET_SMDS_ADDRESS" },
    { LPA_ERROR_INVALID_EVENT_ID,"LPA_ERROR_INVALID_EVENT_ID" },
    { LPA_ERROR_INVALID_RSP_SERVER_ADDRESS,"LPA_ERROR_INVALID_RSP_SERVER_ADDRESS" },
    { LPA_ERROR_INVALID_EVENT_ENTRIES,"LPA_ERROR_INVALID_EVENT_ENTRIES" },
    { LPA_ERROR_NO_EVENT_RECORD_FOUND,"LPA_ERROR_NO_EVENT_RECORD_FOUND" },          // This error code is now obsolete since V1.6
    { LPA_ERROR_CONFIRMATION_CODE_MISSING_OR_EMPTY,"LPA_ERROR_CONFIRMATION_CODE_MISSING_OR_EMPTY" },
    { LPA_ERROR_SERVER_RETURN_404_STATUS_CODE, "LPA_ERROR_SERVER_RETURN_404_STATUS_CODE" },
    { LPA_ERROR_SERVER_RETURN_500_STATUS_CODE, "LPA_ERROR_SERVER_RETURN_500_STATUS_CODE" },

    
    { SE_MEDIA_ERROR_BROKEN_PIPE, "SE_MEDIA_ERROR_BROKEN_PIPE" },
    { SE_MEDIA_E_CANCELLED, "SE_MEDIA_E_CANCELLED" },
    { SE_MEDIA_E_CANT_DISPOSE, "SE_MEDIA_E_CANT_DISPOSE" },
    { SE_MEDIA_E_CARD_UNSUPPORTED, "SE_MEDIA_E_CARD_UNSUPPORTED" },
    { SE_MEDIA_E_DUPLICATE_READER, "SE_MEDIA_E_DUPLICATE_READER" },
    { SE_MEDIA_E_FILE_NOT_FOUND, "SE_MEDIA_E_FILE_NOT_FOUND" },
    { SE_MEDIA_E_INSUFFICIENT_BUFFER, "SE_MEDIA_E_INSUFFICIENT_BUFFER" },
    { SE_MEDIA_E_INVALID_ATR, "SE_MEDIA_E_INVALID_ATR" },
    { SE_MEDIA_E_INVALID_HANDLE, "SE_MEDIA_E_INVALID_HANDLE" },
    { SE_MEDIA_E_INVALID_PARAMETER, "SE_MEDIA_E_INVALID_PARAMETER" },
    { SE_MEDIA_E_INVALID_TARGET, "SE_MEDIA_E_INVALID_TARGET" },
    { SE_MEDIA_E_INVALID_VALUE, "SE_MEDIA_E_INVALID_VALUE" },
    { SE_MEDIA_E_NO_MEMORY, "SE_MEDIA_E_NO_MEMORY" },
    { SE_MEDIA_E_NO_READERS_AVAILABLE, "SE_MEDIA_E_NO_READERS_AVAILABLE" },
    { SE_MEDIA_E_NO_SMARTCARD, "SE_MEDIA_E_NO_SMARTCARD" },
    { SE_MEDIA_E_NOT_READY, "SE_MEDIA_E_NOT_READY" },
    { SE_MEDIA_E_PROTO_MISMATCH, "SE_MEDIA_E_PROTO_MISMATCH" },
    { SE_MEDIA_E_READER_UNAVAILABLE, "SE_MEDIA_E_READER_UNAVAILABLE" },
    { SE_MEDIA_E_READER_UNSUPPORTED, "SE_MEDIA_E_READER_UNSUPPORTED" },
    { SE_MEDIA_E_SERVER_TOO_BUSY, "SE_MEDIA_E_SERVER_TOO_BUSY" },
    { SE_MEDIA_E_SERVICE_STOPPED, "SE_MEDIA_E_SERVICE_STOPPED" },
    { SE_MEDIA_E_SHARING_VIOLATION, "SE_MEDIA_E_SHARING_VIOLATION" },
    { SE_MEDIA_E_SYSTEM_CANCELLED, "SE_MEDIA_E_SYSTEM_CANCELLED" },
    { SE_MEDIA_E_TIMEOUT, "SE_MEDIA_E_TIMEOUT" },
    { SE_MEDIA_E_UNEXPECTED, "SE_MEDIA_E_UNEXPECTED" },
    { SE_MEDIA_E_UNKNOWN_CARD, "SE_MEDIA_E_UNKNOWN_CARD" },
    { SE_MEDIA_E_UNKNOWN_READER, "SE_MEDIA_E_UNKNOWN_READER" },
    { SE_MEDIA_W_REMOVED_CARD, "SE_MEDIA_W_REMOVED_CARD" },
    { SE_MEDIA_W_RESET_CARD, "SE_MEDIA_W_RESET_CARD" },
    { SE_MEDIA_W_UNSUPPORTED_CARD, "SE_MEDIA_W_UNSUPPORTED_CARD" },
    { SE_MEDIA_E_CHAINING_GET_RESPONSE, "SE_MEDIA_E_CHAINING_GET_RESPONSE" },
    
        
    // Latest entry
    { 0, NULL} // Must be NULL
};

EXPORT_DLL LPA_API_ERROR_DESCRIPTION* lpaExGetListErrorCodeDescription()
{
	return _apiErrorDescriptionList;
}

const char* lpaGetErrorCodeDescription(LPA_API_ERROR apiErrorcode)
{
	char* errorCodeDescription = "Unknown LPA API Error Code";
	size_t index = 0;

	while (_apiErrorDescriptionList[index].ptrApiErrorDescription != NULL)
	{
		if (_apiErrorDescriptionList[index].apiErrorCode == apiErrorcode )
		{
			errorCodeDescription = _apiErrorDescriptionList[index].ptrApiErrorDescription;
			break;
		}
		
		index++;
	}

	return errorCodeDescription;
}
